// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ilsan/ent/menureview"
	"ilsan/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MenuReviewDelete is the builder for deleting a MenuReview entity.
type MenuReviewDelete struct {
	config
	hooks    []Hook
	mutation *MenuReviewMutation
}

// Where appends a list predicates to the MenuReviewDelete builder.
func (mrd *MenuReviewDelete) Where(ps ...predicate.MenuReview) *MenuReviewDelete {
	mrd.mutation.Where(ps...)
	return mrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mrd *MenuReviewDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mrd.sqlExec, mrd.mutation, mrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mrd *MenuReviewDelete) ExecX(ctx context.Context) int {
	n, err := mrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mrd *MenuReviewDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(menureview.Table, sqlgraph.NewFieldSpec(menureview.FieldID, field.TypeInt))
	if ps := mrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mrd.mutation.done = true
	return affected, err
}

// MenuReviewDeleteOne is the builder for deleting a single MenuReview entity.
type MenuReviewDeleteOne struct {
	mrd *MenuReviewDelete
}

// Where appends a list predicates to the MenuReviewDelete builder.
func (mrdo *MenuReviewDeleteOne) Where(ps ...predicate.MenuReview) *MenuReviewDeleteOne {
	mrdo.mrd.mutation.Where(ps...)
	return mrdo
}

// Exec executes the deletion query.
func (mrdo *MenuReviewDeleteOne) Exec(ctx context.Context) error {
	n, err := mrdo.mrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{menureview.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mrdo *MenuReviewDeleteOne) ExecX(ctx context.Context) {
	if err := mrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
