// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"ilsan/ent/menureview"
	"ilsan/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MenuReviewQuery is the builder for querying MenuReview entities.
type MenuReviewQuery struct {
	config
	ctx        *QueryContext
	order      []menureview.OrderOption
	inters     []Interceptor
	predicates []predicate.MenuReview
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MenuReviewQuery builder.
func (mrq *MenuReviewQuery) Where(ps ...predicate.MenuReview) *MenuReviewQuery {
	mrq.predicates = append(mrq.predicates, ps...)
	return mrq
}

// Limit the number of records to be returned by this query.
func (mrq *MenuReviewQuery) Limit(limit int) *MenuReviewQuery {
	mrq.ctx.Limit = &limit
	return mrq
}

// Offset to start from.
func (mrq *MenuReviewQuery) Offset(offset int) *MenuReviewQuery {
	mrq.ctx.Offset = &offset
	return mrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mrq *MenuReviewQuery) Unique(unique bool) *MenuReviewQuery {
	mrq.ctx.Unique = &unique
	return mrq
}

// Order specifies how the records should be ordered.
func (mrq *MenuReviewQuery) Order(o ...menureview.OrderOption) *MenuReviewQuery {
	mrq.order = append(mrq.order, o...)
	return mrq
}

// First returns the first MenuReview entity from the query.
// Returns a *NotFoundError when no MenuReview was found.
func (mrq *MenuReviewQuery) First(ctx context.Context) (*MenuReview, error) {
	nodes, err := mrq.Limit(1).All(setContextOp(ctx, mrq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{menureview.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mrq *MenuReviewQuery) FirstX(ctx context.Context) *MenuReview {
	node, err := mrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MenuReview ID from the query.
// Returns a *NotFoundError when no MenuReview ID was found.
func (mrq *MenuReviewQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mrq.Limit(1).IDs(setContextOp(ctx, mrq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{menureview.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mrq *MenuReviewQuery) FirstIDX(ctx context.Context) int {
	id, err := mrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MenuReview entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MenuReview entity is found.
// Returns a *NotFoundError when no MenuReview entities are found.
func (mrq *MenuReviewQuery) Only(ctx context.Context) (*MenuReview, error) {
	nodes, err := mrq.Limit(2).All(setContextOp(ctx, mrq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{menureview.Label}
	default:
		return nil, &NotSingularError{menureview.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mrq *MenuReviewQuery) OnlyX(ctx context.Context) *MenuReview {
	node, err := mrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MenuReview ID in the query.
// Returns a *NotSingularError when more than one MenuReview ID is found.
// Returns a *NotFoundError when no entities are found.
func (mrq *MenuReviewQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mrq.Limit(2).IDs(setContextOp(ctx, mrq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{menureview.Label}
	default:
		err = &NotSingularError{menureview.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mrq *MenuReviewQuery) OnlyIDX(ctx context.Context) int {
	id, err := mrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MenuReviews.
func (mrq *MenuReviewQuery) All(ctx context.Context) ([]*MenuReview, error) {
	ctx = setContextOp(ctx, mrq.ctx, "All")
	if err := mrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MenuReview, *MenuReviewQuery]()
	return withInterceptors[[]*MenuReview](ctx, mrq, qr, mrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mrq *MenuReviewQuery) AllX(ctx context.Context) []*MenuReview {
	nodes, err := mrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MenuReview IDs.
func (mrq *MenuReviewQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mrq.ctx.Unique == nil && mrq.path != nil {
		mrq.Unique(true)
	}
	ctx = setContextOp(ctx, mrq.ctx, "IDs")
	if err = mrq.Select(menureview.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mrq *MenuReviewQuery) IDsX(ctx context.Context) []int {
	ids, err := mrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mrq *MenuReviewQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mrq.ctx, "Count")
	if err := mrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mrq, querierCount[*MenuReviewQuery](), mrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mrq *MenuReviewQuery) CountX(ctx context.Context) int {
	count, err := mrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mrq *MenuReviewQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mrq.ctx, "Exist")
	switch _, err := mrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mrq *MenuReviewQuery) ExistX(ctx context.Context) bool {
	exist, err := mrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MenuReviewQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mrq *MenuReviewQuery) Clone() *MenuReviewQuery {
	if mrq == nil {
		return nil
	}
	return &MenuReviewQuery{
		config:     mrq.config,
		ctx:        mrq.ctx.Clone(),
		order:      append([]menureview.OrderOption{}, mrq.order...),
		inters:     append([]Interceptor{}, mrq.inters...),
		predicates: append([]predicate.MenuReview{}, mrq.predicates...),
		// clone intermediate query.
		sql:  mrq.sql.Clone(),
		path: mrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Etc string `json:"etc,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MenuReview.Query().
//		GroupBy(menureview.FieldEtc).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mrq *MenuReviewQuery) GroupBy(field string, fields ...string) *MenuReviewGroupBy {
	mrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MenuReviewGroupBy{build: mrq}
	grbuild.flds = &mrq.ctx.Fields
	grbuild.label = menureview.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Etc string `json:"etc,omitempty"`
//	}
//
//	client.MenuReview.Query().
//		Select(menureview.FieldEtc).
//		Scan(ctx, &v)
func (mrq *MenuReviewQuery) Select(fields ...string) *MenuReviewSelect {
	mrq.ctx.Fields = append(mrq.ctx.Fields, fields...)
	sbuild := &MenuReviewSelect{MenuReviewQuery: mrq}
	sbuild.label = menureview.Label
	sbuild.flds, sbuild.scan = &mrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MenuReviewSelect configured with the given aggregations.
func (mrq *MenuReviewQuery) Aggregate(fns ...AggregateFunc) *MenuReviewSelect {
	return mrq.Select().Aggregate(fns...)
}

func (mrq *MenuReviewQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mrq); err != nil {
				return err
			}
		}
	}
	for _, f := range mrq.ctx.Fields {
		if !menureview.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mrq.path != nil {
		prev, err := mrq.path(ctx)
		if err != nil {
			return err
		}
		mrq.sql = prev
	}
	return nil
}

func (mrq *MenuReviewQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MenuReview, error) {
	var (
		nodes = []*MenuReview{}
		_spec = mrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MenuReview).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MenuReview{config: mrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mrq *MenuReviewQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mrq.querySpec()
	_spec.Node.Columns = mrq.ctx.Fields
	if len(mrq.ctx.Fields) > 0 {
		_spec.Unique = mrq.ctx.Unique != nil && *mrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mrq.driver, _spec)
}

func (mrq *MenuReviewQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(menureview.Table, menureview.Columns, sqlgraph.NewFieldSpec(menureview.FieldID, field.TypeInt))
	_spec.From = mrq.sql
	if unique := mrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mrq.path != nil {
		_spec.Unique = true
	}
	if fields := mrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, menureview.FieldID)
		for i := range fields {
			if fields[i] != menureview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mrq *MenuReviewQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mrq.driver.Dialect())
	t1 := builder.Table(menureview.Table)
	columns := mrq.ctx.Fields
	if len(columns) == 0 {
		columns = menureview.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mrq.sql != nil {
		selector = mrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mrq.ctx.Unique != nil && *mrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mrq.predicates {
		p(selector)
	}
	for _, p := range mrq.order {
		p(selector)
	}
	if offset := mrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MenuReviewGroupBy is the group-by builder for MenuReview entities.
type MenuReviewGroupBy struct {
	selector
	build *MenuReviewQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mrgb *MenuReviewGroupBy) Aggregate(fns ...AggregateFunc) *MenuReviewGroupBy {
	mrgb.fns = append(mrgb.fns, fns...)
	return mrgb
}

// Scan applies the selector query and scans the result into the given value.
func (mrgb *MenuReviewGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrgb.build.ctx, "GroupBy")
	if err := mrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MenuReviewQuery, *MenuReviewGroupBy](ctx, mrgb.build, mrgb, mrgb.build.inters, v)
}

func (mrgb *MenuReviewGroupBy) sqlScan(ctx context.Context, root *MenuReviewQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mrgb.fns))
	for _, fn := range mrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mrgb.flds)+len(mrgb.fns))
		for _, f := range *mrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MenuReviewSelect is the builder for selecting fields of MenuReview entities.
type MenuReviewSelect struct {
	*MenuReviewQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mrs *MenuReviewSelect) Aggregate(fns ...AggregateFunc) *MenuReviewSelect {
	mrs.fns = append(mrs.fns, fns...)
	return mrs
}

// Scan applies the selector query and scans the result into the given value.
func (mrs *MenuReviewSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrs.ctx, "Select")
	if err := mrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MenuReviewQuery, *MenuReviewSelect](ctx, mrs.MenuReviewQuery, mrs, mrs.inters, v)
}

func (mrs *MenuReviewSelect) sqlScan(ctx context.Context, root *MenuReviewQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mrs.fns))
	for _, fn := range mrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
