// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ilsan/ent/category"
	"ilsan/ent/menu"
	"ilsan/ent/menureview"
	"ilsan/ent/schema"
	"ilsan/ent/store"
	"ilsan/ent/storereview"
	"ilsan/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[2].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdateAt is the schema descriptor for update_at field.
	categoryDescUpdateAt := categoryFields[3].Descriptor()
	// category.DefaultUpdateAt holds the default value on creation for the update_at field.
	category.DefaultUpdateAt = categoryDescUpdateAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	category.UpdateDefaultUpdateAt = categoryDescUpdateAt.UpdateDefault.(func() time.Time)
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescCreatedAt is the schema descriptor for created_at field.
	menuDescCreatedAt := menuFields[2].Descriptor()
	// menu.DefaultCreatedAt holds the default value on creation for the created_at field.
	menu.DefaultCreatedAt = menuDescCreatedAt.Default.(func() time.Time)
	// menuDescUpdateAt is the schema descriptor for update_at field.
	menuDescUpdateAt := menuFields[3].Descriptor()
	// menu.DefaultUpdateAt holds the default value on creation for the update_at field.
	menu.DefaultUpdateAt = menuDescUpdateAt.Default.(func() time.Time)
	// menu.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	menu.UpdateDefaultUpdateAt = menuDescUpdateAt.UpdateDefault.(func() time.Time)
	menureviewFields := schema.MenuReview{}.Fields()
	_ = menureviewFields
	// menureviewDescCreatedAt is the schema descriptor for created_at field.
	menureviewDescCreatedAt := menureviewFields[2].Descriptor()
	// menureview.DefaultCreatedAt holds the default value on creation for the created_at field.
	menureview.DefaultCreatedAt = menureviewDescCreatedAt.Default.(func() time.Time)
	// menureviewDescUpdateAt is the schema descriptor for update_at field.
	menureviewDescUpdateAt := menureviewFields[3].Descriptor()
	// menureview.DefaultUpdateAt holds the default value on creation for the update_at field.
	menureview.DefaultUpdateAt = menureviewDescUpdateAt.Default.(func() time.Time)
	// menureview.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	menureview.UpdateDefaultUpdateAt = menureviewDescUpdateAt.UpdateDefault.(func() time.Time)
	storeFields := schema.Store{}.Fields()
	_ = storeFields
	// storeDescCreatedAt is the schema descriptor for created_at field.
	storeDescCreatedAt := storeFields[2].Descriptor()
	// store.DefaultCreatedAt holds the default value on creation for the created_at field.
	store.DefaultCreatedAt = storeDescCreatedAt.Default.(func() time.Time)
	// storeDescUpdateAt is the schema descriptor for update_at field.
	storeDescUpdateAt := storeFields[3].Descriptor()
	// store.DefaultUpdateAt holds the default value on creation for the update_at field.
	store.DefaultUpdateAt = storeDescUpdateAt.Default.(func() time.Time)
	// store.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	store.UpdateDefaultUpdateAt = storeDescUpdateAt.UpdateDefault.(func() time.Time)
	storereviewFields := schema.StoreReview{}.Fields()
	_ = storereviewFields
	// storereviewDescCreatedAt is the schema descriptor for created_at field.
	storereviewDescCreatedAt := storereviewFields[2].Descriptor()
	// storereview.DefaultCreatedAt holds the default value on creation for the created_at field.
	storereview.DefaultCreatedAt = storereviewDescCreatedAt.Default.(func() time.Time)
	// storereviewDescUpdateAt is the schema descriptor for update_at field.
	storereviewDescUpdateAt := storereviewFields[3].Descriptor()
	// storereview.DefaultUpdateAt holds the default value on creation for the update_at field.
	storereview.DefaultUpdateAt = storereviewDescUpdateAt.Default.(func() time.Time)
	// storereview.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	storereview.UpdateDefaultUpdateAt = storereviewDescUpdateAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[2].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdateAt is the schema descriptor for update_at field.
	userDescUpdateAt := userFields[3].Descriptor()
	// user.DefaultUpdateAt holds the default value on creation for the update_at field.
	user.DefaultUpdateAt = userDescUpdateAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	user.UpdateDefaultUpdateAt = userDescUpdateAt.UpdateDefault.(func() time.Time)
}
