// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ilsan/ent/predicate"
	"ilsan/ent/storereview"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StoreReviewDelete is the builder for deleting a StoreReview entity.
type StoreReviewDelete struct {
	config
	hooks    []Hook
	mutation *StoreReviewMutation
}

// Where appends a list predicates to the StoreReviewDelete builder.
func (srd *StoreReviewDelete) Where(ps ...predicate.StoreReview) *StoreReviewDelete {
	srd.mutation.Where(ps...)
	return srd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (srd *StoreReviewDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, srd.sqlExec, srd.mutation, srd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (srd *StoreReviewDelete) ExecX(ctx context.Context) int {
	n, err := srd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (srd *StoreReviewDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(storereview.Table, sqlgraph.NewFieldSpec(storereview.FieldID, field.TypeInt))
	if ps := srd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, srd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	srd.mutation.done = true
	return affected, err
}

// StoreReviewDeleteOne is the builder for deleting a single StoreReview entity.
type StoreReviewDeleteOne struct {
	srd *StoreReviewDelete
}

// Where appends a list predicates to the StoreReviewDelete builder.
func (srdo *StoreReviewDeleteOne) Where(ps ...predicate.StoreReview) *StoreReviewDeleteOne {
	srdo.srd.mutation.Where(ps...)
	return srdo
}

// Exec executes the deletion query.
func (srdo *StoreReviewDeleteOne) Exec(ctx context.Context) error {
	n, err := srdo.srd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{storereview.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (srdo *StoreReviewDeleteOne) ExecX(ctx context.Context) {
	if err := srdo.Exec(ctx); err != nil {
		panic(err)
	}
}
