// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// MenuReview is the predicate function for menureview builders.
type MenuReview func(*sql.Selector)

// Store is the predicate function for store builders.
type Store func(*sql.Selector)

// StoreReview is the predicate function for storereview builders.
type StoreReview func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
